# Generated by Django 3.1.3 on 2020-11-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
    ]
